export const supportedSites = [
  "linkedin.com",
  "indeed.com/",
  "glassdoor.com",
  "angel.co/",
  "google.com/search?q=",
  "dice.com/",
  "simplyhired.com/",
  "weworkremotely.com/",
  "remoteok.com/",
  "careerbuilder.com/",
  "authenticjobs.com/",
  "flexjobs.com/",
  "powertofly.com/jobs/",
  "workingnomads.com/jobs",
  "remotetechjobs.com/",
  "hired.com/",
  "jobspresso.co/",
  "justremote.co/",
  "pangian.com/",
  "remotive.com/",
  "ziprecruiter.com/",
];

// export const supportedSites = [
//   'linkedin.com',
//   'https://indeed.com/',
//   'https://glassdoor.com',
//   'https://angel.co/', TO BE DONE
//   'https://google.com/search?q=software+engineeer+jobs&oq=software+engineeer+jobs&aqs=chrome..69i57j0i10i433i457j0i402l2j0i10i131i433l2j0i10i433j0i10l3.2984j0j4&sourceid=chrome&ie=UTF-8&ibp=htl;jobs&sa=X&ved=2ahUKEwjh_LPwv7f5AhX5fjABHT9-A50QudcGKAJ6BAg1ECo&sxsrf=ALiCzsaiuFqw1ASyptXB67JQ1x0hSFTP1g:1659970467470#htivrt=jobs&htidocid=zDA5650giXYAAAAAAAAAAA%3D%3D&fpstate=tldetail',
//   'https://dice.com/',
//   'https://simplyhired.com/',
//   'https://weworkremotely.com/',
//   'https://remoteok.com/', TO BE DONE
//   'https://careerbuilder.com/',
//   'https://authenticjobs.com/',
//   'https://flexjobs.com/',
//   'https://powertofly.com/jobs/',
//   'https://workingnomads.com/jobs',
//   'https://remotetechjobs.com/',
//   'https://hired.com/',
//   'https://jobspresso.co/',
//   'https://justremote.co/',
//   'https://pangian.com/',
//   'https://remotive.com/',
//   'https://ziprecruiter.com/'
// ];
